mq:
  ip: 192.168.0.199
  port: 61613
  user: admin
  pwd: admin
  accept_queues: SPF100001
  register_queue: IFS100001
  status_queue: IFS100030
collect:
  interval: 5
client:
  client_key: A3320000001
log:
  loglevel: debug
